;
; Answering Machine Detection (AMD) Configuration
;

[general]
initial_silence = 2500		; Maximum silence duration before we decide it's a dead line (ms)
greeting = 1500			; Maximum length of a greeting. If longer than this, it's a machine (ms)
after_greeting_silence = 800	; Silence after greeting to detect human vs machine (ms)
total_analysis_time = 5000	; Maximum time allowed for AMD analysis (ms)
min_word_length = 100		; Minimum duration of a word to be considered a word (ms)
between_words_silence = 50	; Minimum duration of silence after a word to consider it complete (ms)
maximum_number_of_words = 3	; Maximum number of words in a greeting. More than this is a machine.
silence_threshold = 256		; Average noise level threshold (0-32767)
